### ISSUE TITLE
Runtime Error 

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#89]
I am geting a runtime error playing with latest release, I used LAA to enable me to use more ram, becouse it was staggering when I played previous release, now I cant even get it to launch.

**Comment by jeffg2k** [comment]
@jhuddle1 did you get this working by reinstalling?  I'd like to close the issue as I'm not aware of any Runtime Error problems, but waiting to hear back.

**Comment by jeffg2k** [comment]
Do you have the new DLC minor factions?  I haven't tested it without the latest DLC.  I just pushed a fix for a bug that was causing an error with minor factions when you would select one of the raid options, but I can't reproduce any problems loading the game.

**Comment by jhuddle1** [comment]
I have minor factions. my issues seem to be the game will stagger, momentarily freeze then unfreeze depending on how many players it has on the map. for instance a small map wll barely do it, the larger ones will do it sparraticly

**Comment by jhuddle1** [comment]
I know when I download the new archive and try to apply it I get a runtime error still. I am running minor factions, IDK what the issue is. I am mostly now running the archive from like 12/3/18 without major issues. I tried taking a screenshot of the issue but I couldnt.

**Comment by jhuddle1** [comment]
OK , not having the runtime issue anymore i think, but  Iam now getting a complete game crash once I start researching/ enter combat..... a little disappointed ..

**Comment by jeffg2k** [comment]
Not sure what the issue is as we can't reproduce it.  If you're still running the Sins of a Solar Empire which had LAA applied to the exe, then I would uninstall Sins and reinstall (or change your runtime to the dev.exe).  Running in dev may also give better indication as to what the issue is.  But I would then delete the entire SGI mod and reinstall using the sync method.  https://github.com/StargateInvasion/SGI/wiki/Installation

**Comment by jhuddle1** [comment]
I am getting 

Failed to find data file 'NPCMinorFactions.playerThemes'. (SubPath = Window) 

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\GameInfo\Gameplay.constants
Label: GameplayConstants
Line Number:1
Line Contents:SinsArchiveVersion 193

Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: isNormalPlayer
Line Number:827
Line Contents:	playerType "Normal"

Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: isRaidingPlayer
Line Number:828
Line Contents:	playerType "Normal"


Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: isInsurgentPlayer
Line Number:829
Line Contents:	playerType "Normal"

Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: isOccupationPlayer
Line Number:830
Line Contents:	playerType "Normal"


Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: isMadVasariPlayer
Line Number:831
Line Contents:	playerType "Normal"



Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: themeGroup
Line Number:832
Line Contents:	playerType "Normal"


Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: themeIndex
Line Number:833
Line Contents:	playerType "Normal"


Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: pictureGroup
Line Number:834
Line Contents:	playerType "Normal"


Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: pictureIndex
Line Number:835
Line Contents:	playerType "Normal"

Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: player
Line Number:836
Line Contents:	playerType "Normal"




Text FileArchive missing Label.

File: D:\JHuddle\Documents\My Games\Ironclad Games\Sins of a Solar Empire Rebellion\Mods-Rebellion v1.85 Dev\SGI\Galaxy\Agamemnon's Bounty.galaxy
Label: templates
Line Number:837
Line Contents:	playerType "Normal"

**Comment by jhuddle1** [comment]
after realizing I hadn't installed minor factions, I installed but got a unusual error when playing as asuran on random , it crashed the game

**Comment by jeffg2k** [comment]
I just pushed an update to GitHub that had a lot of changes, so maybe this will help your issue.

**Comment by jeffg2k** [comment]
@jhuddle1 Based on your last issue report, I assume you got things working?  If so, I'll close the ticket.
